---
title: "SEIRmodel"
author: "PM"
date: "24 März 2020"
output: 
  html_document:
    toc: TRUE
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(deSolve)
require(plotly)
```

# Model with 4 compartments (SEIR)
## Specify Model
```{r}
SEIRmod <- function(Time, State, Pars) {
  with(as.list(c(State,Pars)), {
    beta  <-  R0 * sigmaI

    dSS <- - (beta * SS * II)/N
    dEE <- beta * SS * II / N - sigmaE * EE 
    dII <- sigmaE * EE - sigmaI * II
    dRR <- sigmaI * II

    list(c(dSS, dEE, dII, dRR))
  })
}
```

## Specifiy Parameters and Plot
```{r}
SEIRini <- c(SS=8.25e7, EE=1, II=1, RR=1) 
times   <- seq(0, 50, by=1)   ## in weeks
Pars    <- c(N      = sum(SEIRini),
             R0     = 3,
             sigmaI = .5,      ## recovery rate (per week)
             sigmaE = .9)      ## flow rate from Exposed to Infected (per week)

SEIRsim <- deSolve::ode(y=SEIRini,    times=times, 
                        func=SEIRmod, parms=Pars)

plot_ly(data=as.data.frame(SEIRsim), x=~time, y=~SS,
        name='Susceptible', type='scatter', mode='lines') %>%
  add_trace(y=~EE, name='Exposed')%>% 
  add_trace(y=~II, name='Infected') %>%
  add_trace(y=~RR, name='Recovered') #%>%
  # layout(yaxis=list(type='log', title="Individuals", range=c(0,8)))
```

# Model with 3 compartments (SIR)
## Specify Model
```{r}
SIRmod <- function(Time, State, Pars) {
  with(as.list(c(State,Pars)), {
    beta  <-  R0 * sigmaI

    dSS <- - (beta * SS * II)/N
    dII <- (beta * SS * II)/N - sigmaI * II
    dRR <- sigmaI * II

    list(c(dSS, dII, dRR))
  })
}
```

## Specifiy Parameters and Plot
```{r}
SIRini <- c(SS=8.25e7, II=1, RR=1) 
times   <- seq(0, 50, by=1)   ## in weeks
Pars    <- c(N      = sum(SEIRini),
             R0     = 3,
             sigmaI = .5      ## recovery rate (per week)
            )      

SIRsim <- deSolve::ode(y=SIRini,    times=times, 
                        func=SIRmod, parms=Pars)

plot_ly(data=as.data.frame(SIRsim), x=~time, y=~SS,
        name='Susceptible', type='scatter', mode='lines') %>%
  add_trace(y=~II, name='Infected') %>%
  add_trace(y=~RR, name='Recovered') #%>%
  # layout(yaxis=list(type='log', title="Individuals", range=c(0,8)))
```

<!-- # Model with 7 stages  -->
<!-- ## Specify Model -->
<!-- ```{r} -->
<!-- SEIRmod <- function(Time, State, Pars) { -->
<!--   with(as.list(c(State,Pars)), { -->
<!--     beta  <-  R0 * gammaI -->

<!--     dSS <- - (beta * SS * II)/N -->
<!--     dEE <- beta * SS * II / N - sigma * EE  -->
<!--     dII <- sigma * EE - gammaI * II -->
<!--     dHH <- (1-eta)*II - (1-zeta)*CC - gammaH * HH -->
<!--     dCC <- eps * HH - gammaC * CC  -->
<!--     dDD <- zeta * CC -->
<!--     dRR <- eta * II + (1-eps)*HH -->

<!--     list(c(dSS,dEE,dII,dHH,dCC,dDD,dRR)) -->
<!--   }) -->
<!-- } -->
<!-- ``` -->

<!-- ## Specifiy Parameters  -->
<!-- ```{r} -->
<!-- SEIRini <- c(SS=8.25e7, EE=3e4, II=3e4, HH=0, -->
<!--              CC=0, DD=0, RR=0)  -->
<!-- times   <- seq(0, 104, by=1)   ## in weeks -->
<!-- Pars    <- c(N      = sum(SEIRini), -->
<!--              R0     = 5.5, -->
<!--              gammaI = .5,      ## recovery rate (per week) -->
<!--              gammaH = 10,      ##  -->
<!--              gammaC = 10,      ##  -->
<!--              delta  = 1/50,    ## hospitalisation rate -->
<!--              eps    = 1/10,    ## ICU need -->
<!--              zeta   = 1/5,     ## death rate -->
<!--              eta    = .6,      ## recovery rate  -->
<!--              sigma  = .6)      ## flow rate from Exposed to Infected (per week) -->
<!-- # ``` -->
<!-- #  -->
<!-- # ## Run and plot -->
<!-- # ```{r} -->
<!-- SEIRsim <- deSolve::ode(y=SEIRini,    times=times,  -->
<!--                         func=SEIRmod, parms=Pars) -->

<!-- plot_ly(data=as.data.frame(SEIRsim), x=~time, y=~SS, -->
<!--         name='Susceptible', type='scatter', mode='lines') %>% -->
<!--   add_trace(y=~EE, name='Exposed')%>%  -->
<!--   add_trace(y=~II, name='Infected') %>% -->
<!--   add_trace(y=~HH, name='Hospitalised') %>% -->
<!--   add_trace(y=~CC, name='ICU') %>% -->
<!--   add_trace(y=~DD, name='Dead') %>% -->
<!--   add_trace(y=~RR, name='Recovered') %>% -->
<!--   layout(yaxis=list(type='log',title="Individuals")) -->
<!-- ``` -->

